# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Calander.destroy_all
Ingredient.destroy_all
Month.destroy_all
Category.destroy_all

january = Month.create!(name: 'January', season: 'Winter')
february = Month.create!(name: 'February', season: 'Winter')
march = Month.create!(name: 'March', season: 'Spring')
april = Month.create!(name: 'April', season: 'Spring')
may = Month.create!(name: 'May', season: 'Spring')
june = Month.create!(name: 'June', season: 'Summer')
july = Month.create!(name: 'July', season: 'Summer')
august = Month.create!(name: 'August', season: 'Summer')
september = Month.create!(name: 'September', season: 'Autumn')
october = Month.create!(name: 'October', season: 'Autumn')
november = Month.create!(name: 'November', season: 'Autumn')
december = Month.create!(name: 'December', season: 'Winter')

meat = Category.create!(name: 'Meat')
game = Category.create!(name: 'Game')
fish = Category.create!(name: 'Fish & Shellfish')
veg = Category.create!(name: 'Vegetables')
fruit = Category.create!(name: 'Fruits')
herbs = Category.create!(name: 'Herbs')
foraged = Category.create!(name: 'Foraged')

asparagus = Ingredient.create!(name: 'Asparagus', category_id: veg.id)
Calander.create!(ingredient_id: asparagus.id, month_id: april.id)
Calander.create!(ingredient_id: asparagus.id, month_id: may.id)

baby_leek = Ingredient.create!(name: 'Baby Leeks', category_id: veg.id)
Calander.create!(ingredient_id: baby_leek.id, month_id: september.id)

beetroot = Ingredient.create!(name: 'Beetroot', category_id: veg.id)
Calander.create!(ingredient_id: beetroot.id, month_id: january.id)
Calander.create!(ingredient_id: beetroot.id, month_id: july.id)
Calander.create!(ingredient_id: beetroot.id, month_id: august.id)
Calander.create!(ingredient_id: beetroot.id, month_id: september.id)
Calander.create!(ingredient_id: beetroot.id, month_id: october.id)
Calander.create!(ingredient_id: beetroot.id, month_id: november.id)
Calander.create!(ingredient_id: beetroot.id, month_id: december.id)

broad_bean = Ingredient.create!(name: 'Broad Beans', category_id: veg.id)
Calander.create!(ingredient_id: broad_bean.id, month_id: june.id)
Calander.create!(ingredient_id: broad_bean.id, month_id: july.id)
Calander.create!(ingredient_id: broad_bean.id, month_id: august.id)

brocolli_calabrese = Ingredient.create!(name: 'Brocolli (Calabrese)', category_id: veg.id)
Calander.create!(ingredient_id: brocolli_calabrese.id, month_id: august.id)
Calander.create!(ingredient_id: brocolli_calabrese.id, month_id: september.id)
Calander.create!(ingredient_id: brocolli_calabrese.id, month_id: october.id)

brocolli_purple = Ingredient.create!(name: 'Brocolli (Purple)', category_id: veg.id)
Calander.create!(ingredient_id: brocolli_purple.id, month_id: march.id)
Calander.create!(ingredient_id: brocolli_purple.id, month_id: april.id)

basil = Ingredient.create!(name: 'Basil', category_id: herbs.id)
Calander.create!(ingredient_id: basil.id, month_id: may.id)
Calander.create!(ingredient_id: basil.id, month_id: june.id)
Calander.create!(ingredient_id: basil.id, month_id: july.id)
Calander.create!(ingredient_id: basil.id, month_id: august.id)
Calander.create!(ingredient_id: basil.id, month_id: september.id)

bishops_wood = Ingredient.create!(name: 'Bishops Wood', category_id: foraged.id)
Calander.create!(ingredient_id: bishops_wood.id, month_id: april.id)
Calander.create!(ingredient_id: bishops_wood.id, month_id: may.id)
Calander.create!(ingredient_id: bishops_wood.id, month_id: june.id)
Calander.create!(ingredient_id: bishops_wood.id, month_id: july.id)
Calander.create!(ingredient_id: bishops_wood.id, month_id: august.id)
Calander.create!(ingredient_id: bishops_wood.id, month_id: september.id)

blaeberry = Ingredient.create!(name: 'Blaeberry', category_id: foraged.id)
Calander.create!(ingredient_id: blaeberry.id, month_id: july.id)
Calander.create!(ingredient_id: blaeberry.id, month_id: august.id)
Calander.create!(ingredient_id: blaeberry.id, month_id: september.id)

bramble = Ingredient.create!(name: 'Bramble', category_id: foraged.id)
Calander.create!(ingredient_id: bramble.id, month_id: august.id)
Calander.create!(ingredient_id: bramble.id, month_id: september.id)

cep = Ingredient.create!(name: 'Ceps', category_id: foraged.id)
Calander.create!(ingredient_id: cep.id, month_id: july.id)
Calander.create!(ingredient_id: cep.id, month_id: august.id)
Calander.create!(ingredient_id: cep.id, month_id: september.id)

chanterelle = Ingredient.create!(name: 'Chanterelles', category_id: foraged.id)
Calander.create!(ingredient_id: chanterelle.id, month_id: august.id)
Calander.create!(ingredient_id: chanterelle.id, month_id: september.id)
Calander.create!(ingredient_id: chanterelle.id, month_id: october.id)

chestnut = Ingredient.create!(name: 'Chestnuts', category_id: foraged.id)
Calander.create!(ingredient_id: chestnut.id, month_id: october.id)
Calander.create!(ingredient_id: chestnut.id, month_id: november.id)
Calander.create!(ingredient_id: chestnut.id, month_id: december.id)

chives = Ingredient.create!(name: 'Chives', category_id: herbs.id)
Calander.create!(ingredient_id: chives.id, month_id: march.id)
Calander.create!(ingredient_id: chives.id, month_id: april.id)
Calander.create!(ingredient_id: chives.id, month_id: may.id)
Calander.create!(ingredient_id: chives.id, month_id: june.id)
Calander.create!(ingredient_id: chives.id, month_id: july.id)
Calander.create!(ingredient_id: chives.id, month_id: august.id)
Calander.create!(ingredient_id: chives.id, month_id: september.id)
Calander.create!(ingredient_id: chives.id, month_id: october.id)
Calander.create!(ingredient_id: chives.id, month_id: november.id)

sorrel_common = Ingredient.create!(name: 'Sorrel (Common)', category_id: herbs.id)
Calander.create!(ingredient_id: sorrel_common.id, month_id: march.id)
Calander.create!(ingredient_id: sorrel_common.id, month_id: april.id)
Calander.create!(ingredient_id: sorrel_common.id, month_id: may.id)
Calander.create!(ingredient_id: sorrel_common.id, month_id: june.id)
Calander.create!(ingredient_id: sorrel_common.id, month_id: july.id)
Calander.create!(ingredient_id: sorrel_common.id, month_id: august.id)
Calander.create!(ingredient_id: sorrel_common.id, month_id: september.id)
Calander.create!(ingredient_id: sorrel_common.id, month_id: october.id)
Calander.create!(ingredient_id: sorrel_common.id, month_id: november.id)

coriander = Ingredient.create!(name: 'Coriander', category_id: herbs.id)
Calander.create!(ingredient_id: coriander.id, month_id: april.id)
Calander.create!(ingredient_id: coriander.id, month_id: may.id)

cockle = Ingredient.create!(name: 'Cockle', category_id: fish.id)
Calander.create!(ingredient_id: cockle.id, month_id: january.id)
Calander.create!(ingredient_id: cockle.id, month_id: february.id)
Calander.create!(ingredient_id: cockle.id, month_id: march.id)
Calander.create!(ingredient_id: cockle.id, month_id: april.id)
Calander.create!(ingredient_id: cockle.id, month_id: may.id)
Calander.create!(ingredient_id: cockle.id, month_id: june.id)
Calander.create!(ingredient_id: cockle.id, month_id: july.id)
Calander.create!(ingredient_id: cockle.id, month_id: august.id)
Calander.create!(ingredient_id: cockle.id, month_id: september.id)
Calander.create!(ingredient_id: cockle.id, month_id: october.id)
Calander.create!(ingredient_id: cockle.id, month_id: november.id)
Calander.create!(ingredient_id: cockle.id, month_id: december.id)

cod = Ingredient.create!(name: 'Cod', category_id: fish.id)
Calander.create!(ingredient_id: cod.id, month_id: january.id)
Calander.create!(ingredient_id: cod.id, month_id: may.id)
Calander.create!(ingredient_id: cod.id, month_id: june.id)
Calander.create!(ingredient_id: cod.id, month_id: july.id)
Calander.create!(ingredient_id: cod.id, month_id: august.id)
Calander.create!(ingredient_id: cod.id, month_id: september.id)
Calander.create!(ingredient_id: cod.id, month_id: october.id)
Calander.create!(ingredient_id: cod.id, month_id: november.id)
Calander.create!(ingredient_id: cod.id, month_id: december.id)

coley = Ingredient.create!(name: 'Coley', category_id: fish.id)
Calander.create!(ingredient_id: coley.id, month_id: april.id)
Calander.create!(ingredient_id: coley.id, month_id: may.id)
Calander.create!(ingredient_id: coley.id, month_id: june.id)
Calander.create!(ingredient_id: coley.id, month_id: july.id)
Calander.create!(ingredient_id: coley.id, month_id: august.id)
Calander.create!(ingredient_id: coley.id, month_id: september.id)
Calander.create!(ingredient_id: coley.id, month_id: october.id)
Calander.create!(ingredient_id: coley.id, month_id: november.id)
Calander.create!(ingredient_id: coley.id, month_id: december.id)

crab_brown = Ingredient.create!(name: 'Crab (Brown)', category_id: fish.id)
Calander.create!(ingredient_id: crab_brown.id, month_id: january.id)
Calander.create!(ingredient_id: crab_brown.id, month_id: february.id)
Calander.create!(ingredient_id: crab_brown.id, month_id: march.id)
Calander.create!(ingredient_id: crab_brown.id, month_id: april.id)
Calander.create!(ingredient_id: crab_brown.id, month_id: may.id)
Calander.create!(ingredient_id: crab_brown.id, month_id: june.id)
Calander.create!(ingredient_id: crab_brown.id, month_id: july.id)
Calander.create!(ingredient_id: crab_brown.id, month_id: august.id)
Calander.create!(ingredient_id: crab_brown.id, month_id: september.id)
Calander.create!(ingredient_id: crab_brown.id, month_id: october.id)
Calander.create!(ingredient_id: crab_brown.id, month_id: november.id)
Calander.create!(ingredient_id: crab_brown.id, month_id: december.id)

haddock = Ingredient.create!(name: 'Haddock', category_id: fish.id)
Calander.create!(ingredient_id: haddock.id, month_id: january.id)
Calander.create!(ingredient_id: haddock.id, month_id: february.id)
Calander.create!(ingredient_id: haddock.id, month_id: june.id)
Calander.create!(ingredient_id: haddock.id, month_id: july.id)
Calander.create!(ingredient_id: haddock.id, month_id: august.id)
Calander.create!(ingredient_id: haddock.id, month_id: september.id)
Calander.create!(ingredient_id: haddock.id, month_id: october.id)
Calander.create!(ingredient_id: haddock.id, month_id: november.id)
Calander.create!(ingredient_id: haddock.id, month_id: december.id)

hake = Ingredient.create!(name: 'Hake', category_id: fish.id)
Calander.create!(ingredient_id: hake.id, month_id: march.id)
Calander.create!(ingredient_id: hake.id, month_id: april.id)
Calander.create!(ingredient_id: hake.id, month_id: may.id)
Calander.create!(ingredient_id: hake.id, month_id: june.id)
Calander.create!(ingredient_id: hake.id, month_id: july.id)
Calander.create!(ingredient_id: hake.id, month_id: august.id)
Calander.create!(ingredient_id: hake.id, month_id: september.id)
Calander.create!(ingredient_id: hake.id, month_id: october.id)
Calander.create!(ingredient_id: hake.id, month_id: november.id)

halibut_farmed = Ingredient.create!(name: 'Halibut (Farmed)', category_id: fish.id)
Calander.create!(ingredient_id: halibut_farmed.id, month_id: january.id)
Calander.create!(ingredient_id: halibut_farmed.id, month_id: february.id)
Calander.create!(ingredient_id: halibut_farmed.id, month_id: march.id)
Calander.create!(ingredient_id: halibut_farmed.id, month_id: april.id)
Calander.create!(ingredient_id: halibut_farmed.id, month_id: may.id)
Calander.create!(ingredient_id: halibut_farmed.id, month_id: june.id)
Calander.create!(ingredient_id: halibut_farmed.id, month_id: july.id)
Calander.create!(ingredient_id: halibut_farmed.id, month_id: august.id)
Calander.create!(ingredient_id: halibut_farmed.id, month_id: september.id)
Calander.create!(ingredient_id: halibut_farmed.id, month_id: october.id)
Calander.create!(ingredient_id: halibut_farmed.id, month_id: november.id)
Calander.create!(ingredient_id: halibut_farmed.id, month_id: december.id)

herring = Ingredient.create!(name: 'Herring', category_id: fish.id)
Calander.create!(ingredient_id: herring.id, month_id: june.id)
Calander.create!(ingredient_id: herring.id, month_id: july.id)
Calander.create!(ingredient_id: herring.id, month_id: august.id)
Calander.create!(ingredient_id: herring.id, month_id: september.id)

langoustine = Ingredient.create!(name: 'Langoustine', category_id: fish.id)
Calander.create!(ingredient_id: langoustine.id, month_id: january.id)
Calander.create!(ingredient_id: langoustine.id, month_id: february.id)
Calander.create!(ingredient_id: langoustine.id, month_id: march.id)
Calander.create!(ingredient_id: langoustine.id, month_id: april.id)
Calander.create!(ingredient_id: langoustine.id, month_id: may.id)
Calander.create!(ingredient_id: langoustine.id, month_id: september.id)
Calander.create!(ingredient_id: langoustine.id, month_id: october.id)
Calander.create!(ingredient_id: langoustine.id, month_id: november.id)
Calander.create!(ingredient_id: langoustine.id, month_id: december.id)

lemon_sole = Ingredient.create!(name: 'Lemon Sole', category_id: fish.id)
Calander.create!(ingredient_id: lemon_sole.id, month_id: june.id)
Calander.create!(ingredient_id: lemon_sole.id, month_id: july.id)
Calander.create!(ingredient_id: lemon_sole.id, month_id: august.id)
Calander.create!(ingredient_id: lemon_sole.id, month_id: september.id)
Calander.create!(ingredient_id: lemon_sole.id, month_id: october.id)
Calander.create!(ingredient_id: lemon_sole.id, month_id: november.id)
Calander.create!(ingredient_id: lemon_sole.id, month_id: december.id)

ling = Ingredient.create!(name: 'Ling', category_id: fish.id)
Calander.create!(ingredient_id: ling.id, month_id: may.id)
Calander.create!(ingredient_id: ling.id, month_id: june.id)
Calander.create!(ingredient_id: ling.id, month_id: july.id)

lobster = Ingredient.create!(name: 'Lobster', category_id: fish.id)
Calander.create!(ingredient_id: lobster.id, month_id: april.id)
Calander.create!(ingredient_id: lobster.id, month_id: may.id)
Calander.create!(ingredient_id: lobster.id, month_id: june.id)
Calander.create!(ingredient_id: lobster.id, month_id: july.id)
Calander.create!(ingredient_id: lobster.id, month_id: august.id)
Calander.create!(ingredient_id: lobster.id, month_id: september.id)
Calander.create!(ingredient_id: lobster.id, month_id: october.id)
Calander.create!(ingredient_id: lobster.id, month_id: november.id)
Calander.create!(ingredient_id: lobster.id, month_id: december.id)

mackerel = Ingredient.create!(name: 'Mackerel', category_id: fish.id)
Calander.create!(ingredient_id: mackerel.id, month_id: january.id)
Calander.create!(ingredient_id: mackerel.id, month_id: february.id)
Calander.create!(ingredient_id: mackerel.id, month_id: june.id)
Calander.create!(ingredient_id: mackerel.id, month_id: july.id)
Calander.create!(ingredient_id: mackerel.id, month_id: august.id)
Calander.create!(ingredient_id: mackerel.id, month_id: september.id)
Calander.create!(ingredient_id: mackerel.id, month_id: october.id)
Calander.create!(ingredient_id: mackerel.id, month_id: november.id)

megrim = Ingredient.create!(name: 'Megrim', category_id: fish.id)
Calander.create!(ingredient_id: megrim.id, month_id: january.id)
Calander.create!(ingredient_id: megrim.id, month_id: april.id)
Calander.create!(ingredient_id: megrim.id, month_id: may.id)
Calander.create!(ingredient_id: megrim.id, month_id: june.id)
Calander.create!(ingredient_id: megrim.id, month_id: july.id)
Calander.create!(ingredient_id: megrim.id, month_id: august.id)
Calander.create!(ingredient_id: megrim.id, month_id: september.id)

monkfish = Ingredient.create!(name: 'Monkfish', category_id: fish.id)
Calander.create!(ingredient_id: monkfish.id, month_id: january.id)
Calander.create!(ingredient_id: monkfish.id, month_id: february.id)
Calander.create!(ingredient_id: monkfish.id, month_id: october.id)
Calander.create!(ingredient_id: monkfish.id, month_id: november.id)
Calander.create!(ingredient_id: monkfish.id, month_id: december.id)

mussels = Ingredient.create!(name: 'Mussels', category_id: fish.id)
Calander.create!(ingredient_id: mussels.id, month_id: january.id)
Calander.create!(ingredient_id: mussels.id, month_id: february.id)
Calander.create!(ingredient_id: mussels.id, month_id: june.id)
Calander.create!(ingredient_id: mussels.id, month_id: july.id)
Calander.create!(ingredient_id: mussels.id, month_id: august.id)
Calander.create!(ingredient_id: mussels.id, month_id: september.id)
Calander.create!(ingredient_id: mussels.id, month_id: october.id)
Calander.create!(ingredient_id: mussels.id, month_id: november.id)
Calander.create!(ingredient_id: mussels.id, month_id: december.id)

oyster_native = Ingredient.create!(name: 'Oyster (Native)', category_id: fish.id)
Calander.create!(ingredient_id: oyster_native.id, month_id: january.id)
Calander.create!(ingredient_id: oyster_native.id, month_id: february.id)
Calander.create!(ingredient_id: oyster_native.id, month_id: march.id)
Calander.create!(ingredient_id: oyster_native.id, month_id: april.id)
Calander.create!(ingredient_id: oyster_native.id, month_id: september.id)
Calander.create!(ingredient_id: oyster_native.id, month_id: october.id)
Calander.create!(ingredient_id: oyster_native.id, month_id: november.id)
Calander.create!(ingredient_id: oyster_native.id, month_id: december.id)

oyster_pacific = Ingredient.create!(name: 'Oyster (Pacific)', category_id: fish.id)
Calander.create!(ingredient_id: oyster_pacific.id, month_id: january.id)
Calander.create!(ingredient_id: oyster_pacific.id, month_id: february.id)
Calander.create!(ingredient_id: oyster_pacific.id, month_id: march.id)
Calander.create!(ingredient_id: oyster_pacific.id, month_id: april.id)
Calander.create!(ingredient_id: oyster_pacific.id, month_id: may.id)
Calander.create!(ingredient_id: oyster_pacific.id, month_id: september.id)
Calander.create!(ingredient_id: oyster_pacific.id, month_id: october.id)
Calander.create!(ingredient_id: oyster_pacific.id, month_id: november.id)
Calander.create!(ingredient_id: oyster_pacific.id, month_id: december.id)

plaice = Ingredient.create!(name: 'Plaice', category_id: fish.id)
Calander.create!(ingredient_id: plaice.id, month_id: may.id)
Calander.create!(ingredient_id: plaice.id, month_id: june.id)
Calander.create!(ingredient_id: plaice.id, month_id: july.id)
Calander.create!(ingredient_id: plaice.id, month_id: august.id)
Calander.create!(ingredient_id: plaice.id, month_id: september.id)
Calander.create!(ingredient_id: plaice.id, month_id: october.id)
Calander.create!(ingredient_id: plaice.id, month_id: november.id)
Calander.create!(ingredient_id: plaice.id, month_id: december.id)

pollock = Ingredient.create!(name: 'Pollock', category_id: fish.id)

razor_clams = Ingredient.create!(name: 'Razor Clams', category_id: fish.id)
Calander.create!(ingredient_id: razor_clams.id, month_id: april.id)
Calander.create!(ingredient_id: razor_clams.id, month_id: may.id)
Calander.create!(ingredient_id: razor_clams.id, month_id: june.id)
Calander.create!(ingredient_id: razor_clams.id, month_id: july.id)
Calander.create!(ingredient_id: razor_clams.id, month_id: august.id)
Calander.create!(ingredient_id: razor_clams.id, month_id: september.id)
Calander.create!(ingredient_id: razor_clams.id, month_id: october.id)
Calander.create!(ingredient_id: razor_clams.id, month_id: november.id)

farmed_salmon = Ingredient.create!(name: 'Salmon (Farmed)', category_id: fish.id)
Calander.create!(ingredient_id: farmed_salmon.id, month_id: january.id)
Calander.create!(ingredient_id: farmed_salmon.id, month_id: february.id)
Calander.create!(ingredient_id: farmed_salmon.id, month_id: march.id)
Calander.create!(ingredient_id: farmed_salmon.id, month_id: april.id)
Calander.create!(ingredient_id: farmed_salmon.id, month_id: may.id)
Calander.create!(ingredient_id: farmed_salmon.id, month_id: june.id)
Calander.create!(ingredient_id: farmed_salmon.id, month_id: july.id)
Calander.create!(ingredient_id: farmed_salmon.id, month_id: august.id)
Calander.create!(ingredient_id: farmed_salmon.id, month_id: september.id)
Calander.create!(ingredient_id: farmed_salmon.id, month_id: october.id)
Calander.create!(ingredient_id: farmed_salmon.id, month_id: november.id)
Calander.create!(ingredient_id: farmed_salmon.id, month_id: december.id)

wild_salmon = Ingredient.create!(name: 'Salmon (Wild', category_id: fish.id)
Calander.create!(ingredient_id: wild_salmon.id, month_id: february.id)
Calander.create!(ingredient_id: wild_salmon.id, month_id: march.id)
Calander.create!(ingredient_id: wild_salmon.id, month_id: april.id)
Calander.create!(ingredient_id: wild_salmon.id, month_id: may.id)
Calander.create!(ingredient_id: wild_salmon.id, month_id: june.id)
Calander.create!(ingredient_id: wild_salmon.id, month_id: july.id)
Calander.create!(ingredient_id: wild_salmon.id, month_id: august.id)

scallops = Ingredient.create!(name: 'Scallops', category_id: fish.id)
Calander.create!(ingredient_id: scallops.id, month_id: january.id)
Calander.create!(ingredient_id: scallops.id, month_id: february.id)
Calander.create!(ingredient_id: scallops.id, month_id: march.id)
Calander.create!(ingredient_id: scallops.id, month_id: april.id)
Calander.create!(ingredient_id: scallops.id, month_id: may.id)
Calander.create!(ingredient_id: scallops.id, month_id: june.id)
Calander.create!(ingredient_id: scallops.id, month_id: july.id)
Calander.create!(ingredient_id: scallops.id, month_id: august.id)
Calander.create!(ingredient_id: scallops.id, month_id: september.id)
Calander.create!(ingredient_id: scallops.id, month_id: october.id)
Calander.create!(ingredient_id: scallops.id, month_id: november.id)
Calander.create!(ingredient_id: scallops.id, month_id: december.id)

sea_bass = Ingredient.create!(name: 'Sea Bass', category_id: fish.id)
Calander.create!(ingredient_id: sea_bass.id, month_id: june.id)
Calander.create!(ingredient_id: sea_bass.id, month_id: july.id)
Calander.create!(ingredient_id: sea_bass.id, month_id: august.id)
Calander.create!(ingredient_id: sea_bass.id, month_id: september.id)

sea_trout = Ingredient.create!(name: 'Sea Trout', category_id: fish.id)
Calander.create!(ingredient_id: sea_trout.id, month_id: june.id)
Calander.create!(ingredient_id: sea_trout.id, month_id: july.id)
Calander.create!(ingredient_id: sea_trout.id, month_id: august.id)

sprats = Ingredient.create!(name: 'Sprats', category_id: fish.id)
Calander.create!(ingredient_id: sprats.id, month_id: november.id)
Calander.create!(ingredient_id: sprats.id, month_id: december.id)

squid = Ingredient.create!(name: 'Squid', category_id: fish.id)
Calander.create!(ingredient_id: squid.id, month_id: may.id)
Calander.create!(ingredient_id: squid.id, month_id: june.id)
Calander.create!(ingredient_id: squid.id, month_id: july.id)
Calander.create!(ingredient_id: squid.id, month_id: august.id)
Calander.create!(ingredient_id: squid.id, month_id: september.id)
Calander.create!(ingredient_id: squid.id, month_id: october.id)

surf_clams = Ingredient.create!(name: 'Surf Clams', category_id: fish.id)
Calander.create!(ingredient_id: surf_clams.id, month_id: january.id)
Calander.create!(ingredient_id: surf_clams.id, month_id: february.id)
Calander.create!(ingredient_id: surf_clams.id, month_id: march.id)
Calander.create!(ingredient_id: surf_clams.id, month_id: april.id)
Calander.create!(ingredient_id: surf_clams.id, month_id: may.id)
Calander.create!(ingredient_id: surf_clams.id, month_id: june.id)
Calander.create!(ingredient_id: surf_clams.id, month_id: july.id)
Calander.create!(ingredient_id: surf_clams.id, month_id: august.id)
Calander.create!(ingredient_id: surf_clams.id, month_id: september.id)
Calander.create!(ingredient_id: surf_clams.id, month_id: october.id)
Calander.create!(ingredient_id: surf_clams.id, month_id: november.id)
Calander.create!(ingredient_id: surf_clams.id, month_id: december.id)

rainbow_trout = Ingredient.create!(name: 'Rainbow Trout', category_id: fish.id)
Calander.create!(ingredient_id: rainbow_trout.id, month_id: january.id)
Calander.create!(ingredient_id: rainbow_trout.id, month_id: february.id)
Calander.create!(ingredient_id: rainbow_trout.id, month_id: march.id)
Calander.create!(ingredient_id: rainbow_trout.id, month_id: april.id)
Calander.create!(ingredient_id: rainbow_trout.id, month_id: may.id)
Calander.create!(ingredient_id: rainbow_trout.id, month_id: june.id)
Calander.create!(ingredient_id: rainbow_trout.id, month_id: july.id)
Calander.create!(ingredient_id: rainbow_trout.id, month_id: august.id)
Calander.create!(ingredient_id: rainbow_trout.id, month_id: september.id)
Calander.create!(ingredient_id: rainbow_trout.id, month_id: october.id)
Calander.create!(ingredient_id: rainbow_trout.id, month_id: november.id)
Calander.create!(ingredient_id: rainbow_trout.id, month_id: december.id)

turbot = Ingredient.create!(name: 'Turbot', category_id: fish.id)
Calander.create!(ingredient_id: turbot.id, month_id: may.id)
Calander.create!(ingredient_id: turbot.id, month_id: june.id)
Calander.create!(ingredient_id: turbot.id, month_id: july.id)
Calander.create!(ingredient_id: turbot.id, month_id: august.id)

whiting = Ingredient.create!(name: 'Whiting', category_id: fish.id)
Calander.create!(ingredient_id: whiting.id, month_id: january.id)
Calander.create!(ingredient_id: whiting.id, month_id: february.id)
Calander.create!(ingredient_id: whiting.id, month_id: march.id)
Calander.create!(ingredient_id: whiting.id, month_id: april.id)
Calander.create!(ingredient_id: whiting.id, month_id: may.id)
Calander.create!(ingredient_id: whiting.id, month_id: june.id)
Calander.create!(ingredient_id: whiting.id, month_id: july.id)
Calander.create!(ingredient_id: whiting.id, month_id: august.id)
Calander.create!(ingredient_id: whiting.id, month_id: september.id)
Calander.create!(ingredient_id: whiting.id, month_id: october.id)
Calander.create!(ingredient_id: whiting.id, month_id: november.id)
Calander.create!(ingredient_id: whiting.id, month_id: december.id)

winkles = Ingredient.create!(name: 'Winkles', category_id: fish.id)
Calander.create!(ingredient_id: winkles.id, month_id: january.id)
Calander.create!(ingredient_id: winkles.id, month_id: february.id)
Calander.create!(ingredient_id: winkles.id, month_id: march.id)
Calander.create!(ingredient_id: winkles.id, month_id: april.id)
Calander.create!(ingredient_id: winkles.id, month_id: may.id)
Calander.create!(ingredient_id: winkles.id, month_id: june.id)
Calander.create!(ingredient_id: winkles.id, month_id: july.id)
Calander.create!(ingredient_id: winkles.id, month_id: august.id)
Calander.create!(ingredient_id: winkles.id, month_id: september.id)
Calander.create!(ingredient_id: winkles.id, month_id: october.id)
Calander.create!(ingredient_id: winkles.id, month_id: november.id)
Calander.create!(ingredient_id: winkles.id, month_id: december.id)

witch = Ingredient.create!(name: 'Witch', category_id: fish.id)
Calander.create!(ingredient_id: witch.id, month_id: january.id)
Calander.create!(ingredient_id: witch.id, month_id: february.id)
Calander.create!(ingredient_id: witch.id, month_id: march.id)
Calander.create!(ingredient_id: witch.id, month_id: april.id)
Calander.create!(ingredient_id: witch.id, month_id: september.id)
Calander.create!(ingredient_id: witch.id, month_id: october.id)
Calander.create!(ingredient_id: witch.id, month_id: november.id)
Calander.create!(ingredient_id: witch.id, month_id: december.id)

beef = Ingredient.create!(name: 'Beef', category_id: meat.id)
Calander.create!(ingredient_id: beef.id, month_id: january.id)
Calander.create!(ingredient_id: beef.id, month_id: february.id)
Calander.create!(ingredient_id: beef.id, month_id: march.id)
Calander.create!(ingredient_id: beef.id, month_id: april.id)
Calander.create!(ingredient_id: beef.id, month_id: may.id)
Calander.create!(ingredient_id: beef.id, month_id: june.id)
Calander.create!(ingredient_id: beef.id, month_id: july.id)
Calander.create!(ingredient_id: beef.id, month_id: august.id)
Calander.create!(ingredient_id: beef.id, month_id: september.id)
Calander.create!(ingredient_id: beef.id, month_id: october.id)
Calander.create!(ingredient_id: beef.id, month_id: november.id)
Calander.create!(ingredient_id: beef.id, month_id: december.id)

chicken = Ingredient.create!(name: 'Chicken', category_id: meat.id)
Calander.create!(ingredient_id: chicken.id, month_id: january.id)
Calander.create!(ingredient_id: chicken.id, month_id: february.id)
Calander.create!(ingredient_id: chicken.id, month_id: march.id)
Calander.create!(ingredient_id: chicken.id, month_id: april.id)
Calander.create!(ingredient_id: chicken.id, month_id: may.id)
Calander.create!(ingredient_id: chicken.id, month_id: june.id)
Calander.create!(ingredient_id: chicken.id, month_id: july.id)
Calander.create!(ingredient_id: chicken.id, month_id: august.id)
Calander.create!(ingredient_id: chicken.id, month_id: september.id)
Calander.create!(ingredient_id: chicken.id, month_id: october.id)
Calander.create!(ingredient_id: chicken.id, month_id: november.id)
Calander.create!(ingredient_id: chicken.id, month_id: december.id)

snipe = Ingredient.create!(name: 'Snipe', category_id: game.id)
Calander.create!(ingredient_id: snipe.id, month_id: january.id)
Calander.create!(ingredient_id: snipe.id, month_id: september.id)
Calander.create!(ingredient_id: snipe.id, month_id: october.id)
Calander.create!(ingredient_id: snipe.id, month_id: november.id)
Calander.create!(ingredient_id: snipe.id, month_id: december.id)

goose = Ingredient.create!(name: 'Goose', category_id: game.id)
Calander.create!(ingredient_id: goose.id, month_id: january.id)
Calander.create!(ingredient_id: goose.id, month_id: september.id)
Calander.create!(ingredient_id: goose.id, month_id: october.id)
Calander.create!(ingredient_id: goose.id, month_id: november.id)
Calander.create!(ingredient_id: goose.id, month_id: december.id)

grouse = Ingredient.create!(name: 'Grouse', category_id: game.id)
Calander.create!(ingredient_id: grouse.id, month_id: august.id)
Calander.create!(ingredient_id: grouse.id, month_id: september.id)
Calander.create!(ingredient_id: grouse.id, month_id: october.id)
Calander.create!(ingredient_id: grouse.id, month_id: november.id)
Calander.create!(ingredient_id: grouse.id, month_id: december.id)

guinea_fowl = Ingredient.create!(name: 'Guinea Fowl', category_id: meat.id)
Calander.create!(ingredient_id: guinea_fowl.id, month_id: january.id)
Calander.create!(ingredient_id: guinea_fowl.id, month_id: february.id)
Calander.create!(ingredient_id: guinea_fowl.id, month_id: march.id)
Calander.create!(ingredient_id: guinea_fowl.id, month_id: april.id)
Calander.create!(ingredient_id: guinea_fowl.id, month_id: may.id)
Calander.create!(ingredient_id: guinea_fowl.id, month_id: june.id)
Calander.create!(ingredient_id: guinea_fowl.id, month_id: july.id)
Calander.create!(ingredient_id: guinea_fowl.id, month_id: august.id)
Calander.create!(ingredient_id: guinea_fowl.id, month_id: september.id)
Calander.create!(ingredient_id: guinea_fowl.id, month_id: october.id)
Calander.create!(ingredient_id: guinea_fowl.id, month_id: november.id)
Calander.create!(ingredient_id: guinea_fowl.id, month_id: december.id)

brown_hare = Ingredient.create!(name: 'Hare (Brown)', category_id: game.id)
Calander.create!(ingredient_id: brown_hare.id, month_id: january.id)
Calander.create!(ingredient_id: brown_hare.id, month_id: october.id)
Calander.create!(ingredient_id: brown_hare.id, month_id: november.id)
Calander.create!(ingredient_id: brown_hare.id, month_id: december.id)

mountain_hare = Ingredient.create!(name: 'Hare (Mountain)', category_id: game.id)
Calander.create!(ingredient_id: mountain_hare.id, month_id: january.id)
Calander.create!(ingredient_id: mountain_hare.id, month_id: february.id)
Calander.create!(ingredient_id: mountain_hare.id, month_id: august.id)
Calander.create!(ingredient_id: mountain_hare.id, month_id: september.id)
Calander.create!(ingredient_id: mountain_hare.id, month_id: october.id)
Calander.create!(ingredient_id: mountain_hare.id, month_id: november.id)
Calander.create!(ingredient_id: mountain_hare.id, month_id: december.id)

lamb = Ingredient.create!(name: 'Lamb', category_id: meat.id)
Calander.create!(ingredient_id: lamb.id, month_id: january.id)
Calander.create!(ingredient_id: lamb.id, month_id: june.id)
Calander.create!(ingredient_id: lamb.id, month_id: july.id)
Calander.create!(ingredient_id: lamb.id, month_id: august.id)
Calander.create!(ingredient_id: lamb.id, month_id: september.id)
Calander.create!(ingredient_id: lamb.id, month_id: october.id)
Calander.create!(ingredient_id: lamb.id, month_id: november.id)
Calander.create!(ingredient_id: lamb.id, month_id: december.id)

partridge = Ingredient.create!(name: 'Partridge', category_id: game.id)
Calander.create!(ingredient_id: partridge.id, month_id: january.id)
Calander.create!(ingredient_id: partridge.id, month_id: september.id)
Calander.create!(ingredient_id: partridge.id, month_id: october.id)
Calander.create!(ingredient_id: partridge.id, month_id: november.id)
Calander.create!(ingredient_id: partridge.id, month_id: december.id)

pheasant = Ingredient.create!(name: 'Pheasant', category_id: game.id)
Calander.create!(ingredient_id: pheasant.id, month_id: january.id)
Calander.create!(ingredient_id: pheasant.id, month_id: october.id)
Calander.create!(ingredient_id: pheasant.id, month_id: november.id)
Calander.create!(ingredient_id: pheasant.id, month_id: december.id)

pork = Ingredient.create!(name: 'Pork', category_id: meat.id)
Calander.create!(ingredient_id: pork.id, month_id: january.id)
Calander.create!(ingredient_id: pork.id, month_id: february.id)
Calander.create!(ingredient_id: pork.id, month_id: march.id)
Calander.create!(ingredient_id: pork.id, month_id: april.id)
Calander.create!(ingredient_id: pork.id, month_id: may.id)
Calander.create!(ingredient_id: pork.id, month_id: june.id)
Calander.create!(ingredient_id: pork.id, month_id: july.id)
Calander.create!(ingredient_id: pork.id, month_id: august.id)
Calander.create!(ingredient_id: pork.id, month_id: september.id)
Calander.create!(ingredient_id: pork.id, month_id: october.id)
Calander.create!(ingredient_id: pork.id, month_id: november.id)
Calander.create!(ingredient_id: pork.id, month_id: december.id)

ptarmigan = Ingredient.create!(name: 'Ptarmigan', category_id: game.id)
Calander.create!(ingredient_id: ptarmigan.id, month_id: january.id)
Calander.create!(ingredient_id: ptarmigan.id, month_id: september.id)
Calander.create!(ingredient_id: ptarmigan.id, month_id: october.id)
Calander.create!(ingredient_id: ptarmigan.id, month_id: november.id)
Calander.create!(ingredient_id: ptarmigan.id, month_id: december.id)

wild_rabbit = Ingredient.create!(name: 'Wild Rabbit', category_id: game.id)
Calander.create!(ingredient_id: wild_rabbit.id, month_id: january.id)
Calander.create!(ingredient_id: wild_rabbit.id, month_id: february.id)
Calander.create!(ingredient_id: wild_rabbit.id, month_id: march.id)
Calander.create!(ingredient_id: wild_rabbit.id, month_id: april.id)
Calander.create!(ingredient_id: wild_rabbit.id, month_id: may.id)
Calander.create!(ingredient_id: wild_rabbit.id, month_id: june.id)
Calander.create!(ingredient_id: wild_rabbit.id, month_id: july.id)
Calander.create!(ingredient_id: wild_rabbit.id, month_id: august.id)
Calander.create!(ingredient_id: wild_rabbit.id, month_id: september.id)
Calander.create!(ingredient_id: wild_rabbit.id, month_id: october.id)
Calander.create!(ingredient_id: wild_rabbit.id, month_id: november.id)
Calander.create!(ingredient_id: wild_rabbit.id, month_id: december.id)

roe_deer_hind = Ingredient.create!(name: 'Roe Deer Hind', category_id: game.id)
Calander.create!(ingredient_id: roe_deer_hind.id, month_id: january.id)
Calander.create!(ingredient_id: roe_deer_hind.id, month_id: november.id)
Calander.create!(ingredient_id: roe_deer_hind.id, month_id: december.id)

roe_deer_stag = Ingredient.create!(name: 'Roe Deer Stag', category_id: game.id)
Calander.create!(ingredient_id: roe_deer_stag.id, month_id: july.id)
Calander.create!(ingredient_id: roe_deer_stag.id, month_id: august.id)
Calander.create!(ingredient_id: roe_deer_stag.id, month_id: september.id)

roe_deer_buck = Ingredient.create!(name: 'Roe Deer Buck', category_id: game.id)
Calander.create!(ingredient_id: roe_deer_buck.id, month_id: april.id)
Calander.create!(ingredient_id: roe_deer_buck.id, month_id: may.id)
Calander.create!(ingredient_id: roe_deer_buck.id, month_id: june.id)
Calander.create!(ingredient_id: roe_deer_buck.id, month_id: july.id)
Calander.create!(ingredient_id: roe_deer_buck.id, month_id: august.id)
Calander.create!(ingredient_id: roe_deer_buck.id, month_id: september.id)

roe_deer_doe = Ingredient.create!(name: 'Roe Deer Doe', category_id: game.id)
Calander.create!(ingredient_id: roe_deer_doe.id, month_id: january.id)
Calander.create!(ingredient_id: roe_deer_doe.id, month_id: february.id)
Calander.create!(ingredient_id: roe_deer_doe.id, month_id: march.id)
Calander.create!(ingredient_id: roe_deer_doe.id, month_id: november.id)
Calander.create!(ingredient_id: roe_deer_doe.id, month_id: december.id)

rose_veal = Ingredient.create!(name: 'Rose Veal', category_id: meat.id)
Calander.create!(ingredient_id: rose_veal.id, month_id: january.id)
Calander.create!(ingredient_id: rose_veal.id, month_id: february.id)
Calander.create!(ingredient_id: rose_veal.id, month_id: march.id)
Calander.create!(ingredient_id: rose_veal.id, month_id: april.id)
Calander.create!(ingredient_id: rose_veal.id, month_id: may.id)
Calander.create!(ingredient_id: rose_veal.id, month_id: june.id)
Calander.create!(ingredient_id: rose_veal.id, month_id: july.id)
Calander.create!(ingredient_id: rose_veal.id, month_id: august.id)
Calander.create!(ingredient_id: rose_veal.id, month_id: september.id)
Calander.create!(ingredient_id: rose_veal.id, month_id: october.id)
Calander.create!(ingredient_id: rose_veal.id, month_id: november.id)
Calander.create!(ingredient_id: rose_veal.id, month_id: december.id)

sika_deer_hind = Ingredient.create!(name: 'Sika Deer Hind', category_id: game.id)
Calander.create!(ingredient_id: sika_deer_hind.id, month_id: january.id)
Calander.create!(ingredient_id: sika_deer_hind.id, month_id: november.id)
Calander.create!(ingredient_id: sika_deer_hind.id, month_id: december.id)

sika_deer_stag = Ingredient.create!(name: 'Sika Deer Stag', category_id: game.id)
Calander.create!(ingredient_id: sika_deer_stag.id, month_id: july.id)
Calander.create!(ingredient_id: sika_deer_stag.id, month_id: august.id)
Calander.create!(ingredient_id: sika_deer_stag.id, month_id: september.id)

turkey = Ingredient.create!(name: 'Turkey', category_id: game.id)
Calander.create!(ingredient_id: turkey.id, month_id: december.id)

farmed_venison = Ingredient.create!(name: 'Venison (Farmer)', category_id: game.id)
Calander.create!(ingredient_id: farmed_venison.id, month_id: january.id)
Calander.create!(ingredient_id: farmed_venison.id, month_id: february.id)
Calander.create!(ingredient_id: farmed_venison.id, month_id: march.id)
Calander.create!(ingredient_id: farmed_venison.id, month_id: april.id)
Calander.create!(ingredient_id: farmed_venison.id, month_id: may.id)
Calander.create!(ingredient_id: farmed_venison.id, month_id: june.id)
Calander.create!(ingredient_id: farmed_venison.id, month_id: july.id)
Calander.create!(ingredient_id: farmed_venison.id, month_id: august.id)
Calander.create!(ingredient_id: farmed_venison.id, month_id: september.id)
Calander.create!(ingredient_id: farmed_venison.id, month_id: october.id)
Calander.create!(ingredient_id: farmed_venison.id, month_id: november.id)
Calander.create!(ingredient_id: farmed_venison.id, month_id: december.id)

woodcock = Ingredient.create!(name: 'Woodcock', category_id: game.id)
Calander.create!(ingredient_id: woodcock.id, month_id: january.id)
Calander.create!(ingredient_id: woodcock.id, month_id: september.id)
Calander.create!(ingredient_id: woodcock.id, month_id: october.id)
Calander.create!(ingredient_id: woodcock.id, month_id: november.id)
Calander.create!(ingredient_id: woodcock.id, month_id: december.id)

wood_pigeon = Ingredient.create!(name: 'Wood Pigeon', category_id: game.id)
Calander.create!(ingredient_id: wood_pigeon.id, month_id: january.id)
Calander.create!(ingredient_id: wood_pigeon.id, month_id: february.id)
Calander.create!(ingredient_id: wood_pigeon.id, month_id: march.id)
Calander.create!(ingredient_id: wood_pigeon.id, month_id: april.id)
Calander.create!(ingredient_id: wood_pigeon.id, month_id: may.id)
Calander.create!(ingredient_id: wood_pigeon.id, month_id: june.id)
Calander.create!(ingredient_id: wood_pigeon.id, month_id: july.id)
Calander.create!(ingredient_id: wood_pigeon.id, month_id: august.id)
Calander.create!(ingredient_id: wood_pigeon.id, month_id: september.id)
Calander.create!(ingredient_id: wood_pigeon.id, month_id: october.id)
Calander.create!(ingredient_id: wood_pigeon.id, month_id: november.id)
Calander.create!(ingredient_id: wood_pigeon.id, month_id: december.id)

wild_duck = Ingredient.create!(name: 'Wild Duck', category_id: game.id)
Calander.create!(ingredient_id: wild_duck.id, month_id: january.id)
Calander.create!(ingredient_id: wild_duck.id, month_id: september.id)
Calander.create!(ingredient_id: wild_duck.id, month_id: october.id)
Calander.create!(ingredient_id: wild_duck.id, month_id: november.id)
Calander.create!(ingredient_id: wild_duck.id, month_id: december.id)

apple = Ingredient.create!(name: 'Apple', category_id: fruit.id)
Calander.create!(ingredient_id: apple.id, month_id: september.id)
Calander.create!(ingredient_id: apple.id, month_id: october.id)
Calander.create!(ingredient_id: apple.id, month_id: november.id)
Calander.create!(ingredient_id: apple.id, month_id: december.id)
Calander.create!(ingredient_id: apple.id, month_id: january.id)

blackcurrant = Ingredient.create!(name: 'Blackcurrant', category_id: fruit.id)
Calander.create!(ingredient_id: blackcurrant.id, month_id: june.id)
Calander.create!(ingredient_id: blackcurrant.id, month_id: july.id)
Calander.create!(ingredient_id: blackcurrant.id, month_id: august.id)

blueberry = Ingredient.create!(name: 'Blueberry', category_id: fruit.id)
Calander.create!(ingredient_id: blueberry.id, month_id: july.id)
Calander.create!(ingredient_id: blueberry.id, month_id: august.id)
Calander.create!(ingredient_id: blueberry.id, month_id: september.id)

bramble = Ingredient.create!(name: 'Bramble (cultivated', category_id: fruit.id)
Calander.create!(ingredient_id: bramble.id, month_id: august.id)
Calander.create!(ingredient_id: bramble.id, month_id: september.id)

cherry = Ingredient.create!(name: 'Cherry', category_id: fruit.id)
Calander.create!(ingredient_id: cherry.id, month_id: june.id)

damson = Ingredient.create!(name: 'Damson', category_id: fruit.id)
Calander.create!(ingredient_id: damson.id, month_id: september.id)

elderberry = Ingredient.create!(name: 'Elderberry', category_id: fruit.id)
Calander.create!(ingredient_id: elderberry.id, month_id: september.id)
Calander.create!(ingredient_id: elderberry.id, month_id: october.id)

gooseberry = Ingredient.create!(name: 'Gooseberry', category_id: fruit.id)
Calander.create!(ingredient_id: gooseberry.id, month_id: june.id)
Calander.create!(ingredient_id: gooseberry.id, month_id: july.id)
Calander.create!(ingredient_id: gooseberry.id, month_id: august.id)

greengage = Ingredient.create!(name: 'Greengage', category_id: fruit.id)
Calander.create!(ingredient_id: greengage.id, month_id: august.id)

jostaberry = Ingredient.create!(name: 'Jostaberry', category_id: fruit.id)
Calander.create!(ingredient_id: jostaberry.id, month_id: june.id)
Calander.create!(ingredient_id: jostaberry.id, month_id: july.id)
Calander.create!(ingredient_id: jostaberry.id, month_id: august.id)

loganberry = Ingredient.create!(name: 'Loganberry', category_id: fruit.id)
Calander.create!(ingredient_id: loganberry.id, month_id: july.id)
Calander.create!(ingredient_id: loganberry.id, month_id: august.id)

pear = Ingredient.create!(name: 'Pear', category_id: fruit.id)
Calander.create!(ingredient_id: pear.id, month_id: august.id)
Calander.create!(ingredient_id: pear.id, month_id: september.id)
Calander.create!(ingredient_id: pear.id, month_id: october.id)
Calander.create!(ingredient_id: pear.id, month_id: november.id)
Calander.create!(ingredient_id: pear.id, month_id: december.id)

plum = Ingredient.create!(name: 'Plum', category_id: fruit.id)
Calander.create!(ingredient_id: plum.id, month_id: july.id)
Calander.create!(ingredient_id: plum.id, month_id: august.id)
Calander.create!(ingredient_id: plum.id, month_id: september.id)

raspberry = Ingredient.create!(name: 'Raspberry', category_id: fruit.id)
Calander.create!(ingredient_id: raspberry.id, month_id: june.id)
Calander.create!(ingredient_id: raspberry.id, month_id: july.id)
Calander.create!(ingredient_id: raspberry.id, month_id: august.id)
Calander.create!(ingredient_id: raspberry.id, month_id: september.id)

redcurrant = Ingredient.create!(name: 'Redcurrant', category_id: fruit.id)
Calander.create!(ingredient_id: redcurrant.id, month_id: june.id)
Calander.create!(ingredient_id: redcurrant.id, month_id: july.id)
Calander.create!(ingredient_id: redcurrant.id, month_id: august.id)

rhubarb = Ingredient.create!(name: 'Rhubarb', category_id: fruit.id)
Calander.create!(ingredient_id: rhubarb.id, month_id: may.id)
Calander.create!(ingredient_id: rhubarb.id, month_id: june.id)
Calander.create!(ingredient_id: rhubarb.id, month_id: july.id)

strawberry = Ingredient.create!(name: 'Strawberry', category_id: fruit.id)
Calander.create!(ingredient_id: strawberry.id, month_id: june.id)
Calander.create!(ingredient_id: strawberry.id, month_id: july.id)
Calander.create!(ingredient_id: strawberry.id, month_id: august.id)
Calander.create!(ingredient_id: strawberry.id, month_id: september.id)

tayberry = Ingredient.create!(name: 'Tayberry', category_id: fruit.id)
Calander.create!(ingredient_id: tayberry.id, month_id: june.id)
Calander.create!(ingredient_id: tayberry.id, month_id: july.id)
Calander.create!(ingredient_id: tayberry.id, month_id: august.id)

tomato = Ingredient.create!(name: 'Tomato', category_id: fruit.id)
Calander.create!(ingredient_id: tomato.id, month_id: june.id)
Calander.create!(ingredient_id: tomato.id, month_id: july.id)
Calander.create!(ingredient_id: tomato.id, month_id: august.id)
Calander.create!(ingredient_id: tomato.id, month_id: september.id)
