# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Calander.destroy_all
Ingredient.destroy_all
Month.destroy_all
Category.destroy_all

january = Month.create!(name: 'January', season: 'Winter')
february = Month.create!(name: 'February', season: 'Winter')
march = Month.create!(name: 'March', season: 'Spring')
april = Month.create!(name: 'April', season: 'Spring')
may = Month.create!(name: 'May', season: 'Spring')
june = Month.create!(name: 'June', season: 'Summer')
july = Month.create!(name: 'July', season: 'Summer')
august = Month.create!(name: 'August', season: 'Summer')
september = Month.create!(name: 'September', season: 'Autumn')
october = Month.create!(name: 'October', season: 'Autumn')
november = Month.create!(name: 'November', season: 'Autumn')
december = Month.create!(name: 'December', season: 'Winter')

meat = Category.create!(name: 'Meat')
game = Category.create!(name: 'Game')
fish = Category.create!(name: 'Fish & Shellfish')
veg = Category.create!(name: 'Vegetables')
fruit = Category.create!(name: 'Fruits')
herbs = Category.create!(name: 'Herbs')
foraged = Category.create!(name: 'Foraged')

asparagus = Ingredient.create!(name: 'Asparagus', category_id: veg.id)
Calander.create!(ingredient_id: asparagus.id, month_id: april.id)
Calander.create!(ingredient_id: asparagus.id, month_id: may.id)

baby_leek = Ingredient.create!(name: 'Baby Leeks', category_id: veg.id)
Calander.create!(ingredient_id: baby_leek.id, month_id: september.id)

beetroot = Ingredient.create!(name: 'Beetroot', category_id: veg.id)
Calander.create!(ingredient_id: beetroot.id, month_id: january.id)
Calander.create!(ingredient_id: beetroot.id, month_id: july.id)
Calander.create!(ingredient_id: beetroot.id, month_id: august.id)
Calander.create!(ingredient_id: beetroot.id, month_id: september.id)
Calander.create!(ingredient_id: beetroot.id, month_id: october.id)
Calander.create!(ingredient_id: beetroot.id, month_id: november.id)
Calander.create!(ingredient_id: beetroot.id, month_id: december.id)

broad_bean = Ingredient.create!(name: 'Broad Beans', category_id: veg.id)
Calander.create!(ingredient_id: broad_bean.id, month_id: june.id)
Calander.create!(ingredient_id: broad_bean.id, month_id: july.id)
Calander.create!(ingredient_id: broad_bean.id, month_id: august.id)

brocolli_calabrese = Ingredient.create!(name: 'Brocolli (Calabrese)', category_id: veg.id)
Calander.create!(ingredient_id: brocolli_calabrese.id, month_id: august.id)
Calander.create!(ingredient_id: brocolli_calabrese.id, month_id: september.id)
Calander.create!(ingredient_id: brocolli_calabrese.id, month_id: october.id)

brocolli_purple = Ingredient.create!(name: 'Brocolli (Purple)', category_id: veg.id)
Calander.create!(ingredient_id: brocolli_purple.id, month_id: march.id)
Calander.create!(ingredient_id: brocolli_purple.id, month_id: april.id)

basil = Ingredient.create!(name: 'Basil', category_id: herbs.id)
Calander.create!(ingredient_id: basil.id, month_id: may.id)
Calander.create!(ingredient_id: basil.id, month_id: june.id)
Calander.create!(ingredient_id: basil.id, month_id: july.id)
Calander.create!(ingredient_id: basil.id, month_id: august.id)
Calander.create!(ingredient_id: basil.id, month_id: september.id)

bishops_wood = Ingredient.create!(name: 'Bishops Wood', category_id: foraged.id)
Calander.create!(ingredient_id: bishops_wood.id, month_id: april.id)
Calander.create!(ingredient_id: bishops_wood.id, month_id: may.id)
Calander.create!(ingredient_id: bishops_wood.id, month_id: june.id)
Calander.create!(ingredient_id: bishops_wood.id, month_id: july.id)
Calander.create!(ingredient_id: bishops_wood.id, month_id: august.id)
Calander.create!(ingredient_id: bishops_wood.id, month_id: september.id)

blaeberry = Ingredient.create!(name: 'Blaeberry', category_id: foraged.id)
Calander.create!(ingredient_id: blaeberry.id, month_id: july.id)
Calander.create!(ingredient_id: blaeberry.id, month_id: august.id)
Calander.create!(ingredient_id: blaeberry.id, month_id: september.id)

bramble = Ingredient.create!(name: 'Bramble', category_id: foraged.id)
Calander.create!(ingredient_id: bramble.id, month_id: august.id)
Calander.create!(ingredient_id: bramble.id, month_id: september.id)

cep = Ingredient.create!(name: 'Ceps', category_id: foraged.id)
Calander.create!(ingredient_id: cep.id, month_id: july.id)
Calander.create!(ingredient_id: cep.id, month_id: august.id)
Calander.create!(ingredient_id: cep.id, month_id: september.id)

chanterelle = Ingredient.create!(name: 'Chanterelles', category_id: foraged.id)
Calander.create!(ingredient_id: chanterelle.id, month_id: august.id)
Calander.create!(ingredient_id: chanterelle.id, month_id: september.id)
Calander.create!(ingredient_id: chanterelle.id, month_id: october.id)

chestnut = Ingredient.create!(name: 'Chestnuts', category_id: foraged.id)
Calander.create!(ingredient_id: chestnut.id, month_id: october.id)
Calander.create!(ingredient_id: chestnut.id, month_id: november.id)
Calander.create!(ingredient_id: chestnut.id, month_id: december.id)

chives = Ingredient.create!(name: 'Chives', category_id: herbs.id)
Calander.create!(ingredient_id: chives.id, month_id: march.id)
Calander.create!(ingredient_id: chives.id, month_id: april.id)
Calander.create!(ingredient_id: chives.id, month_id: may.id)
Calander.create!(ingredient_id: chives.id, month_id: june.id)
Calander.create!(ingredient_id: chives.id, month_id: july.id)
Calander.create!(ingredient_id: chives.id, month_id: august.id)
Calander.create!(ingredient_id: chives.id, month_id: september.id)
Calander.create!(ingredient_id: chives.id, month_id: october.id)
Calander.create!(ingredient_id: chives.id, month_id: november.id)

sorrel_common = Ingredient.create!(name: 'Sorrel (Common)', category_id: herbs.id)
Calander.create!(ingredient_id: sorrel_common.id, month_id: march.id)
Calander.create!(ingredient_id: sorrel_common.id, month_id: april.id)
Calander.create!(ingredient_id: sorrel_common.id, month_id: may.id)
Calander.create!(ingredient_id: sorrel_common.id, month_id: june.id)
Calander.create!(ingredient_id: sorrel_common.id, month_id: july.id)
Calander.create!(ingredient_id: sorrel_common.id, month_id: august.id)
Calander.create!(ingredient_id: sorrel_common.id, month_id: september.id)
Calander.create!(ingredient_id: sorrel_common.id, month_id: october.id)
Calander.create!(ingredient_id: sorrel_common.id, month_id: november.id)

cockle = Ingredient.create!(name: 'Cockle', category_id: fish.id)
Calander.create!(ingredient_id: cockle.id, month_id: january.id)
Calander.create!(ingredient_id: cockle.id, month_id: february.id)
Calander.create!(ingredient_id: cockle.id, month_id: march.id)
Calander.create!(ingredient_id: cockle.id, month_id: april.id)
Calander.create!(ingredient_id: cockle.id, month_id: may.id)
Calander.create!(ingredient_id: cockle.id, month_id: june.id)
Calander.create!(ingredient_id: cockle.id, month_id: july.id)
Calander.create!(ingredient_id: cockle.id, month_id: august.id)
Calander.create!(ingredient_id: cockle.id, month_id: september.id)
Calander.create!(ingredient_id: cockle.id, month_id: october.id)
Calander.create!(ingredient_id: cockle.id, month_id: november.id)
Calander.create!(ingredient_id: cockle.id, month_id: december.id)

cod = Ingredient.create!(name: 'Cod', category_id: fish.id)
Calander.create!(ingredient_id: cod.id, month_id: january.id)
Calander.create!(ingredient_id: cod.id, month_id: may.id)
Calander.create!(ingredient_id: cod.id, month_id: june.id)
Calander.create!(ingredient_id: cod.id, month_id: july.id)
Calander.create!(ingredient_id: cod.id, month_id: august.id)
Calander.create!(ingredient_id: cod.id, month_id: september.id)
Calander.create!(ingredient_id: cod.id, month_id: october.id)
Calander.create!(ingredient_id: cod.id, month_id: november.id)
Calander.create!(ingredient_id: cod.id, month_id: december.id)

coley = Ingredient.create!(name: 'Coley', category_id: fish.id)
Calander.create!(ingredient_id: coley.id, month_id: april.id)
Calander.create!(ingredient_id: coley.id, month_id: may.id)
Calander.create!(ingredient_id: coley.id, month_id: june.id)
Calander.create!(ingredient_id: coley.id, month_id: july.id)
Calander.create!(ingredient_id: coley.id, month_id: august.id)
Calander.create!(ingredient_id: coley.id, month_id: september.id)
Calander.create!(ingredient_id: coley.id, month_id: october.id)
Calander.create!(ingredient_id: coley.id, month_id: november.id)
Calander.create!(ingredient_id: coley.id, month_id: december.id)

sea_trout = Ingredient.create!(name: 'Sea Trout', category_id: fish.id)
Calander.create!(ingredient_id: sea_trout.id, month_id: june.id)
Calander.create!(ingredient_id: sea_trout.id, month_id: july.id)
Calander.create!(ingredient_id: sea_trout.id, month_id: august.id)

beef = Ingredient.create!(name: 'Beef', category_id: meat.id)
Calander.create!(ingredient_id: beef.id, month_id: january.id)
Calander.create!(ingredient_id: beef.id, month_id: february.id)
Calander.create!(ingredient_id: beef.id, month_id: march.id)
Calander.create!(ingredient_id: beef.id, month_id: april.id)
Calander.create!(ingredient_id: beef.id, month_id: may.id)
Calander.create!(ingredient_id: beef.id, month_id: june.id)
Calander.create!(ingredient_id: beef.id, month_id: july.id)
Calander.create!(ingredient_id: beef.id, month_id: august.id)
Calander.create!(ingredient_id: beef.id, month_id: september.id)
Calander.create!(ingredient_id: beef.id, month_id: october.id)
Calander.create!(ingredient_id: beef.id, month_id: november.id)
Calander.create!(ingredient_id: beef.id, month_id: december.id)

chicken = Ingredient.create!(name: 'Chicken', category_id: meat.id)
Calander.create!(ingredient_id: chicken.id, month_id: january.id)
Calander.create!(ingredient_id: chicken.id, month_id: february.id)
Calander.create!(ingredient_id: chicken.id, month_id: march.id)
Calander.create!(ingredient_id: chicken.id, month_id: april.id)
Calander.create!(ingredient_id: chicken.id, month_id: may.id)
Calander.create!(ingredient_id: chicken.id, month_id: june.id)
Calander.create!(ingredient_id: chicken.id, month_id: july.id)
Calander.create!(ingredient_id: chicken.id, month_id: august.id)
Calander.create!(ingredient_id: chicken.id, month_id: september.id)
Calander.create!(ingredient_id: chicken.id, month_id: october.id)
Calander.create!(ingredient_id: chicken.id, month_id: november.id)
Calander.create!(ingredient_id: chicken.id, month_id: december.id)

snipe = Ingredient.create!(name: 'Snipe', category_id: game.id)
Calander.create!(ingredient_id: snipe.id, month_id: january.id)
Calander.create!(ingredient_id: snipe.id, month_id: september.id)
Calander.create!(ingredient_id: snipe.id, month_id: october.id)
Calander.create!(ingredient_id: snipe.id, month_id: november.id)
Calander.create!(ingredient_id: snipe.id, month_id: december.id)

goose = Ingredient.create!(name: 'Goose', category_id: game.id)
Calander.create!(ingredient_id: goose.id, month_id: january.id)
Calander.create!(ingredient_id: goose.id, month_id: september.id)
Calander.create!(ingredient_id: goose.id, month_id: october.id)
Calander.create!(ingredient_id: goose.id, month_id: november.id)
Calander.create!(ingredient_id: goose.id, month_id: december.id)

turkey = Ingredient.create!(name: 'Turkey', category_id: game.id)
Calander.create!(ingredient_id: turkey.id, month_id: december.id)

wild_duck = Ingredient.create!(name: 'Wild Duck', category_id: game.id)
Calander.create!(ingredient_id: wild_duck.id, month_id: january.id)
Calander.create!(ingredient_id: wild_duck.id, month_id: september.id)
Calander.create!(ingredient_id: wild_duck.id, month_id: october.id)
Calander.create!(ingredient_id: wild_duck.id, month_id: november.id)
Calander.create!(ingredient_id: wild_duck.id, month_id: december.id)

apple = Ingredient.create!(name: 'Apple', category_id: fruit.id)
Calander.create!(ingredient_id: apple.id, month_id: september.id)
Calander.create!(ingredient_id: apple.id, month_id: october.id)
Calander.create!(ingredient_id: apple.id, month_id: november.id)
Calander.create!(ingredient_id: apple.id, month_id: december.id)
Calander.create!(ingredient_id: apple.id, month_id: january.id)

blackcurrant = Ingredient.create!(name: 'Blackcurrant', category_id: fruit.id)
Calander.create!(ingredient_id: blackcurrant.id, month_id: june.id)
Calander.create!(ingredient_id: blackcurrant.id, month_id: july.id)
Calander.create!(ingredient_id: blackcurrant.id, month_id: august.id)

blueberry = Ingredient.create!(name: 'Blueberry', category_id: fruit.id)
Calander.create!(ingredient_id: blueberry.id, month_id: july.id)
Calander.create!(ingredient_id: blueberry.id, month_id: august.id)
Calander.create!(ingredient_id: blueberry.id, month_id: september.id)

bramble = Ingredient.create!(name: 'Bramble (cultivated', category_id: fruit.id)
Calander.create!(ingredient_id: bramble.id, month_id: august.id)
Calander.create!(ingredient_id: bramble.id, month_id: september.id)

cherry = Ingredient.create!(name: 'Cherry', category_id: fruit.id)
Calander.create!(ingredient_id: cherry.id, month_id: june.id)

damson = Ingredient.create!(name: 'Damson', category_id: fruit.id)
Calander.create!(ingredient_id: damson.id, month_id: september.id)

